api:
  autodiscoveryID: "000000"

https:
  host: "0.0.0.0"
  port: "8081"
  
until:
  successful:
    maxretries: "3"
    timebetween: "3000"
    
sys:
  fis:
    host: "localhost"
    port: "8082"
    basepath: "/api"
    responseTimeout: "60000"
  salesforce-financial:
    host: "localhost"
    port: "8083"
    basepath: "/api"
    responseTimeout: "60000"
  salesforce-customers:
    host: "localhost"
    port: "8084"
    basepath: "/api"
    responseTimeout: "60000"

process:
  scheduler:
    all:
      cron: "* * * * * ? 2099"
    bankaccounts:
      cron: "* * * * * ? 2099"
    customers:
      cron: "* * * * * ? 2099"
    transactions:
      cron: "* * * * * ? 2099"