# API specification
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  autodiscovery: "00000"

  
# Listener configuration
https:
  host: "0.0.0.0"
  port: "8080"

#FIS Request Configuration
fis:
  host: "api-gw-uat.fisglobal.com"
  port: "443"
  tokenPath: "/token"
  response-timeout: "60000"
  connection-idle-timeout: "3000"
  http-frequency: "5000"
  http-reconnection-attempts: "2"
  consumer:
    key: "Overridden during deployment"
    secret: "Overridden during deployment"
  getAllCustomersPath: "/rest/medapimobile/v1/customers/search"
  getCustomerByIdPath: "/rest/inv-customer/v1.2/customers/{customerId}"
  getContactByIdPath: "/rest/inv-customer/v1.2/customers/{customerId}/contactPoints"
  getAccountByCustomerIdPath: "/rest/medapimobile/v1/customers/{customerId}/accounts"
  getAccountByAccountIdPath: "/rest/medapimobile/v1/customers/{customerId}/accounts/{accountId}/deposit"
  getTransactionByAccountIdPath: "/rest/medapimobile/v1/customers/{customerId}/accounts/{accountId}/deposithistory"
  
# Retry configuration 
retry:
  fis:
    delayMillisecs: "3000"
    numRetries: "1"      