#%RAML 1.0 NamedExample
{
  "severity": "ERROR",
  "code": "SYSGEN5000",
  "message": "The system failed to process the request",
  "parameters": [
    {
      "paramName": "ResourceName",
      "paramValue": "/accounts"
    },
    {
      "paramName": "ObjectId",
      "paramValue": "00582245"
    }
  ]
}
