#%RAML 1.0 NamedExample
{
  "errorCode": "415",
  "errorMessage": "The server is refusing to the request because it is not in a format supported by the target resource.",
  "transactionId": "dd960082-abbf-47c2-8c65-f18eeb35848b",
  "timeStamp": "2019-09-30T15:27:49.274Z"
}
