#%RAML 1.0 NamedExample
{
  "errorCode": "406",
  "errorMessage": "The requested resource cannot generate acceptable content according to the Accept headers sent in the request.",
  "transactionId": "dd960082-abbf-47c2-8c65-f18eeb35848b",
  "timeStamp": "2019-09-30T15:27:49.274Z"
}
