# API specification
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  # Replace with respective autodiscovery id
  autodiscoveryID: "16422513"
  
# Listener configuration
https:
  host: "0.0.0.0"
  port: "8080"

# API Configuration
salesforce-customer-sys-api:
  http-listener:
    path: "/api/*"

# Salesforce configuration
sfdc:
  user_name: "Username overridden at deploy time"
  token: "token overridden at deploy time"
  password: "password overridden at deploy time"
  
# retry
retry:
  sfdc:
    timebetween: "2000"
    maxretries: "2"  

# Customer configuration
customer:
  party-type-individual: "individual"
  party-type-organization: "organization"