#%RAML 1.0 NamedExample
{
  "errorCode": "500",
  "errorMessage": "The server was unable to process the request due to an internal error",
  "transactionId": "dd960082-abbf-47c2-8c65-f18eeb35848b",
  "timeStamp": "2019-09-30T15:27:49.274Z"
}
