#%RAML 1.0
title: FINS Salesforce Financial System API
description: System API for working with Salesforce Financial Services Cloud objects
version: v1
mediaType: application/json

uses: 
  GlobalResources: ./accelerator-global-resources/2.2.0/accelerator-global-resources.raml
  BankingTypes: ./fins-banking-library/1.0.8/fins-banking-library.raml
 
securedBy: [ GlobalResources.BasicAuth ]

/ping:
  get:
    is: [ GlobalResources.PingResponse ]
    description: Get the current health status of this API.

/accounts:
  description: Base resource for managing bank accounts
  get:
    is: [ GlobalResources.ErrorResponses, GlobalResources.Pageable, GlobalResources.Trackable ]
    description: Find one or more financial accounts by matching one of the criteria supplied. When multiple criteria are provided the precedence order is to match on FSC account identifier and then external identifier. Can also filter by customer ID and limit to accounts created or updated during a given time period. Actual account objects returned will be of specific types (e.g., CheckingAccount).
    queryParameters:
      accountId?:
        type: string
        description: Lookup by FSC identifier
      externalId?:
        type: string
        description: Lookup by an external identifier (e.g., global account ID)
      customerId?:
        type: string
        description: Lookup by customer identifier
      fromDate?:
        type: datetime
        description: Include accounts created or updated on or after this date and time
      toDate?:
        type: datetime
        description: Include accounts created or updated on or before this date and time
    responses:
      200:
        body:
          application/json:
            type: BankingTypes.Account[]
  post:
    is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable, GlobalResources.Locatable ]
    description: Create a new account in FSC. The referenced customer must already exist.
    body:
      application/json:
        type: BankingTypes.Account
    responses: 
      200:
        body: 
          application/json:
            type: GlobalResources.BasicResponse

  /{accountId}:
    get:
      is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable ]
      description: Return details for an existing account.
      responses:
        200:
          body:
            application/json:
              type: BankingTypes.Account
    patch:
      is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable ]
      description: Update details for an existing account. Returns a complete version of the updated account.
      body:
        application/json:
          type: BankingTypes.Account
      responses:
        200:
          body: 
            application/json:
              type: BankingTypes.Account

    /transactions:
      get:
        is: [ GlobalResources.ErrorResponses, GlobalResources.Pageable, GlobalResources.Trackable ]
        description: Retrieve transactions for an account, optionally for a given transaction type and/or for a given time period. Actual transaction objects returned will be of specific types (e.g., DebitTransaction).
        queryParameters:
          transactionType?:
            type: string
            description: Filter by transaction type (e.g., DebitTransaction)
          transactionSubType?: 
            type: string
            description: Filter by transaction sub-type (e.g., CASH)
          postedDate?:
            type: date-only
            description: Get all transactions posted on a specific date
          fromDate?:
            type: datetime
            description: Get transactions created or updated on or after this date and time
          toDate?:
            type: datetime
            description: Get transactions created or updated on or before this date and time
        responses:
          200:
            body:
              application/json:
                type: BankingTypes.Transaction[]
      post:
        is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable, GlobalResources.Locatable ]
        description: Create a new transaction for this account.
        body:
          application/json:
            type: BankingTypes.Transaction
        responses:
          201:
            body:
              application/json:
                type: GlobalResources.BasicResponse

      /{transactionId}:
        get:
          is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable ]
          description: Return details for a specific transaction.
          responses:
            200:
              body:
                application/json:
                  type: BankingTypes.Transaction
        patch:
          is: [ GlobalResources.ErrorResponses, GlobalResources.Trackable ]
          description: Update a transaction to mark or unmark it as disputed.
          body:
            application/json:
              type: BankingTypes.Transaction
          responses:
            200:
              body:
                application/json:
                  type: GlobalResources.BasicResponse
